### ISSUE TITLE
theme: exception for records having no authors

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire-next#2966]
https://sentry.inspirehep.net/inspire-sentry/inspire-qa/issues/297/

```
UndefinedError: 'inspirehep.modules.records.wrappers.LiteratureRecord object' has no attribute 'authors'
(14 additional frame(s) were not displayed)
...
  File "/opt/inspire/src/inspire/inspirehep/modules/theme/templates/inspirehep_theme/page.html", line 87, in block "page_body"
    {%- block body %}
  File "/opt/inspire/src/inspire/inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_detailed.tpl", line 41, in block "body"
    {{ render_record_authors(record, is_brief=false, number_of_displayed_authors=25) }}
  File "jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/opt/inspire/src/inspire/inspirehep/modules/theme/templates/inspirehep_theme/format/record/Inspire_Default_HTML_general_macros.tpl", line 74, in template
    {% if record.authors[0] %}
  File "jinja2/environment.py", line 411, in getitem
    return obj[argument]

UndefinedError: 'inspirehep.modules.records.wrappers.LiteratureRecord object' has no attribute 'authors'
```

**Comment by michamos** [comment]
Probably caused by https://github.com/inspirehep/inspire-next/commit/ff6153a87d4134bd89b69ff0017c154b10551f12#diff-64aed3610e8fa6818ec7b47edb0fe01eR74
